### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by Charlottevm**

### CODE REVIEW

**Comment by Charlottevm** [comment]
Thank you both for the comments and I am glad you like our personal touch @antw ! I have fixed the broken links using 'yarn build', handy to know for next time. Hopefully now everything is ready to be merged :-)

**Comment by antw** [comment]
Thanks @Charlottevm! I took a look at the preview of the changes, and I really like it. It's much better organised and feels like something people might actually read now. 😆 

There are only two negatives that stand out to me:

* The molecules documentation has been moved to "4. Modelling principles". It think this still belongs in "For contributors": it's technical documentation aimed at Quintel staff, not end-users. We could rename the page to "Configuring molecule flows" if that makes things clearer?

* I'm not sure about removing the dedicated sidebars for the "For contributors" and "API reference" sections. The audiences for these parts of the documentation will be very different to those viewing the user manual:

  * For contributors: Aimed at other Quintel staff and people who might want to run the model for themselves.
  * API reference: For those who interact directly with the API.

  Personally I think these should be kept separate, as they used to be. It's my hope that "For contributors" will be filled with many more articles in the future – aimed at Qs – and the API reference will also have new pages added as docs are ported from [the old page](https://energytransitionmodel.com/api).

  It's not a deal-breaker for me, but I think I preferred these when they were separate from the user-facing docs. I'm curious how others feel? @ChaelKruip @michieldenhaan @noracato?

  If we do keep this change, note that some of the pages from these sections no longer have links from the sidebar: 

  * Contrib → [Writing documentation](https://docs.energytransitionmodel.com/contrib/authoring-docs)
  * API Reference → Endpoints → [Everything](https://docs.energytransitionmodel.com/api/custom-curves)

**Comment by Charlottevm** [comment]
@antw good points! 

- I will switch back the 'molecules' documentation (if @ChaelKruip also agrees). 
- The removal of the top-buttons was based on the decision that the documentation is currently primarily used for the introduction and detailed infopages (based on google analytics), plus if you are a contributor you often know the ETM/documentation better and might not need the extra button on top. Without the top-bar the documentation becomes a more minimal and less confusing for regular users. These were some of the considerations, but if it is crucial for navigation I can switch it back to where it was!

_Old (with top-buttons):_ 
afbeelding

_New (without top-buttons):_
afbeelding

**Comment by ChaelKruip** [comment]
> It's not a deal-breaker for me, but I think I preferred these when they were separate from the user-facing docs. I'm curious how others feel? @ChaelKruip @michieldenhaan @noracato?

I don't have a strong preference either way to be honest. 
I really appreciate all the good work put into this lately though!

**Comment by antw** [comment]
> The removal of the top-buttons was based on the decision that the documentation is currently primarily used for the introduction and detailed infopages (based on google analytics)

Personally I'm fine with removing the links from the header. I agree with your reasoning that those who want to read the "For contributors" or "API reference" sections can find the links on the sidebar.

However I think I wasn't very clear: what I preferred about the old version is that those two sections had their own sidebars. This allowed us to highlight the content relevant to those sections while hiding all the stuff that wasn't. If you're visiting the API reference, you probably aren't interested in the sections on the main sidebar. Previously we had three:

* The main sidebar: shown for all content in /docs/main, and had *links* to the contributor and API sections.
* The "For contributors" sidebar: shown for content in /docs/contrib
* The "API reference" sidebar: shown for content in /docs/api
  Screenshot 2021-02-09 at 10 33 37

I realise this seems very nitpicky, given that these two sections are small and infrequently visited, but it's my hope that they eventually get filled out with many more pages.

**Comment by noracato** [comment]
Looks great @Charlottevm!

I get what you are saying @antw, it would be nice to get some contributor documentation up as well in the future.

For now, maybe an extra sidebar layer will do as well, if you don't want to clutter the header? Or will that make the sidebar too 'deeply' layered?

Screenshot 2021-02-09 at 11 40 22

**Comment by michieldenhaan** [comment]
I prefer the old top button version as well, think it's good to keep the main menu as simple as possible both for everyday users (who aren't going to click on section 5 and 6) and pro users (who aren't going to click on section 1-4 for technical info).

**Comment by Charlottevm** [comment]
I now understand what you mean @antw, I have changed it back (or you have technically ;-). Thank you for looking at it! If there are any other comments let me know, if not then we can merge :-)

**Review by antw — APPROVED** [review]
@Charlottevm No other comments from me. It looks fantastic. :tada:

**Review by michieldenhaan — APPROVED** [review]
Agree, big big upgrade :)

**Pull request merged**
