### PR TITLE
Add documentation for outdoor temperature slider

### PR DESCRIPTION
**Pull request by michieldenhaan**

### CODE REVIEW

**Comment by redekok** [comment]
LGTM! A few remarks:

- The "below" link doesn't work on my local machine.

image

- Furthermore, should we explain why hot water is assumed to be temperature independent? I guess I wouldn't assume it to be temperature independent. However, te profiles we use simply don't allow us to make this demand temperature dependent. 

- Nitpick: could we use the formula text format for the cool_format relationship?

image

- And another nitpick: is the link to the wikipedia page on degree days supposed to be be displayed as "1"?

image

- And one last nitpick: should we explain the reddish line? Is this the average temperature?

image

**Comment by michieldenhaan** [comment]
Thanks @redekok! I've added your suggestions.

> Furthermore, should we explain why hot water is assumed to be temperature independent? I guess I wouldn't assume it to be temperature independent. However, te profiles we use simply don't allow us to make this demand temperature dependent.

I think the main consideration is that taking a shower or doing the dishes is not directly related to outdoor temperature. There may be some behavioural and energetic effects (people taking a hot shower when they are cold, a lower base temperature of water supply etc) but we don't have data on this and I suspect these effects to be pretty minor. I'm not sure whether we should add this to the docs, the file is already quite long and information dense.

> And one last nitpick: should we explain the reddish line? Is this the average temperature?
This picture is from the old documentation page. The red line shows the 'heating degree days' limit which we don't use any more. I highlighted the part that is still relevant now. Ideally we should generate a new picture with the heating part removed.

**Comment by ChaelKruip** [comment]
> Ideally we should generate a new picture with the heating part removed.

I could do this if you want. Let me know!

**Comment by michieldenhaan** [comment]
If that doesn't take you too much time, yes please!

**Comment by ChaelKruip** [comment]
Figure_1

**Pull request merged**
